version: "3"
services:

  station_ar_1:
    build:
      context: .
      dockerfile: station/Dockerfile
    networks:
      - stations
    environment:
      - STATION_NUM=1
      - STATIONS_TOTAL=3
      - COUNTRY=AR

  station_ar_2:
    build:
      context: .
      dockerfile: station/Dockerfile
    networks:
      - stations
    environment:
      - STATION_NUM=2
      - STATIONS_TOTAL=3
      - COUNTRY=AR

  station_ar_3:
    build:
      context: .
      dockerfile: station/Dockerfile
    networks:
    - stations
    environment:
    - STATION_NUM=3
    - STATIONS_TOTAL=3
    - COUNTRY=AR

  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile
    depends_on:
      - station_ar_1
      - station_ar_2
      - station_ar_3
    networks:
      - stations
    environment:
      - COUNTRY=AR
      - FREQUENCY=100
      - STATIONS_TOTAL=3

networks:
  stations: